sudo: false

language: node_js
node_js:
  - 6
  - 8
  - 8.9.3
  - node
script: npm run ci

before_install:
  - npm i -g npm

install:
  - npm ci

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.npm
